version: "3.9"
services:
  backend_tp1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    links:
      - bd_backend
    volumes:
      - .:/home/Backend
  bd_backend:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bdpwb
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
